add routing #14
craigshoemaker/livewire pull request #16
Opened 2020-09-01 14:54 UTC by cephalin

2020-09-01 14:56 UTC, cephalin commented
@craigshoemaker I changed the naming `vscode-extensions` to `extensions` so it simplifies the routing logic. If there were some reason it has to be `vscode-extensions`, let me know.

2020-09-05 01:35 UTC, craigshoemaker requested changes, later dismissed
Looking great! 🎉 

Just one change to the `Foo` class name.

2020-09-05 01:35 UTC, craigshoemaker commented on ui/src/main.js
> +})
```suggestion
const BlankTemplate = { template: '<div></div>' }

const router = new VueRouter({
  mode: 'history', // use hashless route
  routes: [
    { path: '/getting-started', name: "getting-started", component: BlankTemplate },
    { path: '/tools', name: "tools", component: BlankTemplate },
    { path: '/extensions', name: "extensions", component: BlankTemplate },
    { path: '/', redirect: '/getting-started'},
    { path: "*", redirect: '/getting-started'}
  ]
})
```
Can we use something a bit more descriptive as a class name?

2020-09-09 19:45 UTC, craigshoemaker approved these changes

2020-09-09 19:45 UTC, merged